name: metalleke.github.io
theme: jekyll-theme-architect
description: metalleke.github.io
title: metalleke.github.io
author:
  name: Kevin Van Ryckegem
  bio: Software Engineer
footer-links:
  github: metalleke
  linkedin: kevinvr
url: metalleke.github.io
